id: P009225
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:28:52.359364
source_metadata:
  id: bdr:W23633
  title: ཟིན་བྲིས་བཅུ་གསུམ
  author: ''
  volumes:
    1b0c53cdc16d47618211f16c52eeb36f:
      image_group_id: I1KG463
      title: ''
      volume_number: 1
      total_pages: 940
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
