id: I13A8D499
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:33:48+00:00'
last_modified: '2022-06-08T09:30:28.744742+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23633
  title: ཟིན་བྲིས་བཅུ་གསུམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    46F9:
      image_group_id: I1KG463
      title: ''
      total_pages: 940
      order: 1
      base_file: 46F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
